# Generated by Django 5.0 on 2026-08-26 16:37

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('color', models.CharField(default='#3498DB', max_length=7, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7810412c-3bb0-4477-87a4-fc75da13011a'), editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='عنوان سند')),
                ('document_number', models.CharField(help_text='شماره یکتا برای شناسایی سند', max_length=50, unique=True, verbose_name='شماره سند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.documents.models.document_upload_path, verbose_name='فایل')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل بر اساس بایت')),
                ('file_type', models.CharField(blank=True, help_text='مثل : pdf, xlsx, docx, jpg', max_length=50, null=True, verbose_name='نوع فایل')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('ARCHIVED', 'بایگانی'), ('EXPIRED', 'منقضی'), ('DRAFT', 'پیش نویس')], default='ACTIVE', max_length=20, verbose_name='وضعیت')),
                ('access_level', models.CharField(choices=[('PUBLIC', 'عمومی'), ('INTERNAL', 'داخلی'), ('CONFIDENTIAL', 'محرمانه'), ('SECRET', 'سری')], default='INTERNAL', max_length=20, verbose_name='سطح دسترسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('expire_date', models.DateField(blank=True, help_text='بعد از این تاریخ سند منقضی می شود', null=True, verbose_name='تاریخ  انقضا')),
                ('document_date', models.DateField(blank=True, help_text='تاریخ رسمی سند', null=True, verbose_name='تاریخ سند')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='فیلدهای فرم پویا اینجا ذخیره می شوند', verbose_name='داده های اضافی')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL, verbose_name='مسئول پیگیری')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد  شده  توسط')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'ایجاد'), ('VIEW', 'مشاهده'), ('EDIT', 'ویرایش'), ('DELETE', 'حذف'), ('DOWNLOAD', 'دانلود'), ('CHECKOUT', 'خروج از قفسه'), ('CHECKIN', 'ورود به قفسه'), ('SHARE', 'اشتراک\u200cگذاری'), ('EXPIRE', 'انقضا')], max_length=20, verbose_name='عملیات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.document', verbose_name='سند')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ سند',
                'verbose_name_plural': 'لاگ اسناد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام پوشه')),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='حداکثر عمق = 10', verbose_name='سطح')),
                ('color', models.CharField(default='#4A90D9', help_text='کد هگز رنگ', max_length=7, verbose_name='رنگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folder', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.folder', verbose_name='پوشه مادر')),
            ],
            options={
                'verbose_name': 'پوشه',
                'verbose_name_plural': 'پوشه ها',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.folder', verbose_name='پوشه'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.tag', verbose_name='برچسب ها'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='شماره نسخه')),
                ('file', models.FileField(upload_to='document_versions/', verbose_name='فایل نسخه')),
                ('change_note', models.TextField(blank=True, null=True, verbose_name='یادداشت تغییر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادشده توسط')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='سند')),
            ],
            options={
                'verbose_name': 'نسخه سند',
                'verbose_name_plural': 'نسخه\u200cهای سند',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='documents_d_title_ccf306_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_number'], name='documents_d_documen_dbcf06_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'created_at'], name='documents_d_status_64808e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expire_date'], name='documents_d_expire__a9268f_idx'),
        ),
    ]
