# Generated by Django 5.0 on 2026-08-26 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام فرم')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب فرم',
                'verbose_name_plural': ' قالب های فرم',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='برچسب')),
                ('field_name', models.CharField(max_length=100, verbose_name='نام فیلد (انگلیسی)')),
                ('field_type', models.CharField(choices=[('TEXT', 'متن'), ('NUMBER', 'عدد'), ('SELECT', 'انتخاب از لیست'), ('DATE', 'تاریخ'), ('CHECKBOX', 'چکباکس'), ('FILE', 'فایل'), ('TEXTAREA', 'متن بلند')], default='TEXT', max_length=20, verbose_name='نوع فیلد')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری؟')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('options', models.JSONField(blank=True, default=list, help_text='برای نوع SELECT: ["گزینه ۱", "گزینه ۲"]', verbose_name='گزینه\u200cها')),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن راهنما')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_builder.formschema', verbose_name='فرم')),
            ],
            options={
                'verbose_name': 'فیلد فرم',
                'verbose_name_plural': 'فیلدهای فرم',
                'ordering': ['order'],
            },
        ),
    ]
